### ISSUE TITLE
complete the lab collection

### ISSUE THREAD

**Issue by zisisvakras** [zisisvakras/mips-tool-pack#8]

**Comment by StavrosGous** [comment]
εχω 3 θεματα παλια λυμενα και το template 4 αρχειο. 
να προσθεσω και ενα labs/themata και labs/templates ? η να τα βαλω ολα στο labs/misc που ειπες;

**Comment by StavrosGous** [comment]
επισης lab5 εννοεις την 5η εργαστηριακη ασκηση ή το 5ο κατα σειρα εργαστηριο; Δηλαδη εγω την 5_3 την εκανα στο 7ο εργαστηριο. θα την βαλω στο lab7 ή στο lab5;

**Comment by zisisvakras** [comment]
5η εργαστηριακη ασκηση

**Comment by zisisvakras** [comment]
Είναι οκ, αλλα τα comments θελουν δουλεια, οποτε μπορεις κοιτα το

**Comment by StavrosGous** [comment]
Θες να είναι πιο περιεκτικά ή απλά καλύτερη στοίχιση;

**Comment by zisisvakras** [comment]
- Θα πρεπει να διαγραφουν τα μεγαλα comment blocks μιας και ειναι αχρηστα
- Θα πρεπει να γινει καλη στοιχιση τον comments οπως και στα υπολοιπα αρχεια του repo
